apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
  labels:
    app: my-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
        - name: my-web-app-container
          image: 089042446418.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest
          ports:
            - containerPort: 8000