apiVersion: apps/v1
kind: Deployment
metadata:
  name: Project
  labels:
    app: Project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Project
  template:
    metadata:
      labels:
        app: Project
    spec:
      containers:
        - name: Project-container
          image: 089042446418.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest
          ports:
            - containerPort: 8000
