apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-repo
  namespace: backend-app
  labels:
    app: backend-repo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-repo
  template:
    metadata:
      labels:
        app: backend-repo
    spec:
      containers:
      - name: backend-repo
        image: PLACEHOLDER_IMAGE_URI  # This will be replaced by GitHub Actions
        ports:
        - containerPort: 8000
        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-repo-service
  namespace: backend-app
  labels:
    app: backend-repo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: backend-repo
